config/routes.rb
Rails.application.routes.draw do

  resources :lights
  devise_for :users
  root 'home#index'
  get 'home/index'


  get 'home/about'


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/light.rb
class Light < ApplicationRecord

	belongs_to :user
		has_attached_file :image, :styles => { :medium => "300x300>",
		:thumb => "100x100>" }

	validates_attachment_content_type :image, :content_type => /\Aimage\/.*\Z/

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

         has_many :lights
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end

  def about
  end
  
end

app/controllers/lights_controller.rb
class LightsController < ApplicationController
  before_action :set_light, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index, :show]
  before_action :correct_user, only: [:edit, :update, :destroy]

  # GET /lights
  # GET /lights.json
  def index
    @lights = Light.all
  end

  # GET /lights/1
  # GET /lights/1.json
  def show
  end

  # GET /lights/new
  def new
    @light = current_user.lights.build

  end

  # GET /lights/1/edit
  def edit
  end

  # POST /lights
  # POST /lights.json
  def create
    @light = current_user.lights.build (light_params)

    respond_to do |format|
      if @light.save
        format.html { redirect_to @light, notice: 'Light was successfully created.' }
        format.json { render :show, status: :created, location: @light }
      else
        format.html { render :new }
        format.json { render json: @light.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /lights/1
  # PATCH/PUT /lights/1.json
  def update
    respond_to do |format|
      if @light.update(light_params)
        format.html { redirect_to @light, notice: 'Light was successfully updated.' }
        format.json { render :show, status: :ok, location: @light }
      else
        format.html { render :edit }
        format.json { render json: @light.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /lights/1
  # DELETE /lights/1.json
  def destroy
    @light.destroy
    respond_to do |format|
      format.html { redirect_to lights_url, notice: 'Light was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_light
      @light = Light.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def light_params
      params.require(:light).permit(:description, :image)
    end
  def correct_user
    @light = current_user.lights.find_by(id: params[:id])
    redirect_to lights_path, notice: "Not authorised to edit this light" if @light.nil?
  end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/lights_helper.rb
module LightsHelper
end

app/views/home/_header.html.erb
<nav class="navbar navbar-default">
  <div class="container">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to 'Discipled', root_path, class: 'navbar-brand' %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav navbar-right">  
        <!--li class="active"><a href="#">Link <span class="sr-only">(current)</span></a></li> -->
        <li><%= link_to 'Home', root_path %></li>
        <li><%= link_to 'About', home_about_path %></li>
        <li><%= link_to 'Show Lights', lights_path %></li>
        <% if user_signed_in? %>
          <li><%= link_to 'Edit Profile', edit_user_registration_path%></li>
          <li><%= link_to 'Logout', destroy_user_session_path, method: :delete %></li>
            <% else %>
          <li><%= link_to 'Login', new_user_session_path %></li>
          <li><%= link_to 'Join', new_user_registration_path %></li>
            <% end %>
      </ul>
      <!--<form class="navbar-form navbar-left">
        <div class="form-group">
          <input type="text" class="form-control" placeholder="Search">
        </div>
        <button type="submit" class="btn btn-default">Submit</button>
      </form> -->
      <!--<ul class="nav navbar-nav navbar-right">
        <li><a href="#">Link</a></li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Dropdown <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><a href="#">Action</a></li>
            <li><a href="#">Another action</a></li>
            <li><a href="#">Something else here</a></li>
            <li role="separator" class="divider"></li>
            <li><a href="#">Separated link</a></li>
          </ul> -->
        </li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/home/about.html.erb
<h1>About Me...</h1>
<p>My Name is Nathan and I wanted to create this app to give christians an opportunity to share what it looks like to walk like Christ. To show love to others who don't deserve our love and sacrifice of ourselves to try and make this world a better place</p>

app/views/home/index.html.erb
<h1>Welcome to Discipled</h1>
<p>A place to move forward the gospel of Christ</p>


<div class="jumbotron">
  <h1>May your light shine bright everywhere you go</h1>
  <p>...</p>
  <p><a class="btn btn-primary btn-lg" href="#" role="button">Learn more</a>
  <%= link_to 'About Us', home_about_path, class: 'btn btn-primary btn-lg'%></p>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Discipled</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  	<%= render 'home/header' %>
    <div class= "container">
      <% flash.each do |name, msg| %>
        <%= content_tag(:div, msg,class: "alert alert-info") %>
        <% end %>
    <%= yield %>
  </div>
  </body>
</html>

app/views/lights/_form.html.erb
<%= form_for @light, html: {multipart: true } do |f| %>
  <% if light.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(light.errors.count, "error") %> prohibited this light from being saved:</h2>

     <ul>
      <% light.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul> 
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :description %>
    <%= f.text_field :description, class: "form-control" %>
  </div>

  <div class="actions"> 
    <%= f.submit %>
  </div>

  <div class= "form-group">
      <%= f.label :image %>
      <%= f.file_field :image, class: "form-control" %>
  </div>

<% end %>

app/views/lights/edit.html.erb
<h1>Editing Light</h1>

<%= render 'form', light: @light %>

<%= link_to 'Show', @light %> |
<%= link_to 'Back', lights_path %>

app/views/lights/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Lights</h1>

<table>
  <thead>
    <tr>
      <th>Description</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @lights.each do |light| %>
      <tr>
        <td><%= image_tag light.image.url(:medium) %></td>
        <td><%= light.description %></td>
        
        <td><%= link_to 'Show', light %></td>
        <% if light.user == current_user %>
        <td><%= link_to 'Edit', edit_light_path(light) %></td>
        <td><%= link_to 'Destroy', light, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Light', new_light_path %>

app/views/lights/new.html.erb
<h1>New Light</h1>

<%= render 'form', light: @light %>

<%= link_to 'Back', lights_path %>

app/views/lights/show.html.erb
<p id="notice"><%= notice %></p>
<%= image_tag @light.image.url(:medium) %>
<br>
  <strong>Description:</strong>
</br>
  <p><%= @light.description %></p>
  
<% if @light.user == current_user %>
<%= link_to 'Edit', edit_light_path(@light) %> 
<% end %>
<%= link_to 'Back', lights_path %>